zalando-zmon/zmon-data-service

Dockerfile
README.md

Although there is a newer version available, I used this one to be consistent across all zmon projects.

Uuse opensource registry

---

config/application.yaml
src/main/java/de/zalando/zmon/dataservice/DataServiceMetrics.java
src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/config/MetricsConfig.java
src/main/java/de/zalando/zmon/dataservice/data/ApplicationMetricsWriter.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDbWorkResultWriter.java
src/main/java/de/zalando/zmon/dataservice/data/MarkWriter.java
src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java
src/main/java/de/zalando/zmon/dataservice/data/RedisMetricsUpdater.java
src/main/java/de/zalando/zmon/dataservice/data/RedisWorkerResultWriter.java
src/test/java/de/zalando/zmon/dataservice/DataServiceLocalIT.java
src/test/java/de/zalando/zmon/dataservice/data/ApplicationMetricsWriterTest.java
src/test/java/de/zalando/zmon/dataservice/data/DataServiceControllerTest.java
src/test/java/de/zalando/zmon/dataservice/data/KairosDbStoreTest.java
src/test/java/de/zalando/zmon/dataservice/data/LogDataWriterTest.java
src/test/java/de/zalando/zmon/dataservice/data/PutDataTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithDefaultCheckServiceTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithNoOpServiceTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxyTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/scheduler/DataCenterControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/scheduler/DataCenterControllerWithDefaultTest.java
src/test/resources/config/application-local-it.yml
src/test/resources/de/zalando/zmon/dataservice/tokeninfo.json
src/test/resources/log4j.xml

'first', use DEBUG level  when tests running

use stringredistemplate, add 'putData' in test, remove unused config

---

.gitignore
src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/RedisMetricsUpdater.java
src/test/java/de/zalando/zmon/dataservice/data/ApplicationMetricsWriterTest.java
src/test/java/de/zalando/zmon/dataservice/data/DataServiceControllerTest.java
src/test/java/de/zalando/zmon/dataservice/data/KairosDbStoreTest.java
src/test/java/de/zalando/zmon/dataservice/data/LogDataWriterTest.java
src/test/java/de/zalando/zmon/dataservice/data/PutDataTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithDefaultCheckServiceTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithNoOpServiceTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxyTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/scheduler/DataCenterControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/scheduler/DataCenterControllerWithDefaultTest.java

F  server port

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/config/SecurityConfig.java
src/main/java/de/zalando/zmon/dataservice/oauth2/AuthenticationCacheLoader.java
src/main/java/de/zalando/zmon/dataservice/oauth2/CacheReadAuthenticationException.java
src/main/java/de/zalando/zmon/dataservice/oauth2/CacheRemovalListener.java
src/main/java/de/zalando/zmon/dataservice/oauth2/CachingTokenInfoResourceServerTokenServices.java

Please have a look at the implementation.

Caching for TokenInfo

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java
src/main/java/de/zalando/zmon/dataservice/data/ProxyWriter.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/DefaultEntitiesService.java
src/main/java/de/zalando/zmon/dataservice/proxies/kairosdb/KairosdbProxy.java
src/main/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxy.java
src/main/java/de/zalando/zmon/dataservice/proxies/scheduler/DefaultSchedulerService.java

Changes:
* use explicit async with proper settings
* remove expectContinue which is not really necessary at all to my understanding.

Changes around proxy behavior

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/proxies/checks/DefaultChecksService.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/DefaultEntitiesService.java

Fixing this temporarily with these timeouts and new executor, not thinking about pool size right now.
This should tackle the threads getting stuck, blocking everything.
@jbellmann FYI

Fix entities/check/alert proxy

---

src/main/java/de/zalando/zmon/dataservice/proxies/checks/ChecksController.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesController.java
src/main/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxy.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/AbstractCheckControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxyTest.java

Remove "/rest" prefix, but keep path mapping for compatibility.

remove /rest path prefix

---

src/main/java/de/zalando/zmon/dataservice/oauth2/BearerToken.java
src/test/java/de/zalando/zmon/dataservice/oauth2/BearerTokenTest.java

Looked like
```
Authorization: Bearer Optional[123]
```

fix Bearer token injection

---

src/main/java/de/zalando/zmon/dataservice/oauth2/BearerToken.java
src/main/java/de/zalando/zmon/dataservice/proxies/checks/DefaultChecksService.java
src/main/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxy.java

Fix token forward for mobile api proxy

---

Dockerfile
src/main/java/de/zalando/zmon/dataservice/config/SecurityConfig.java
src/main/java/de/zalando/zmon/dataservice/proxies/checks/ChecksController.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesController.java
src/main/java/de/zalando/zmon/dataservice/proxies/mobile/MobileApiProxy.java
src/main/resources/config/application.yaml
src/test/java/de/zalando/zmon/dataservice/data/Fixture.java
src/test/resources/config/application-entities.yml
src/test/resources/config/application-it.yml

Remove support for the old "/rest" API path.
Also remove some unused config and code.

Remove legacy /rest path prefix

---

src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java
src/test/java/de/zalando/zmon/dataservice/data/PutDataTest.java

Fixes #45.
* use "try-with-resource".
* cleanup

Issue 45 time period

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java
src/test/java/de/zalando/zmon/dataservice/proxies/KairosDBTest.java

Fix some unallowed chars in metric and key field.

Fixing non kairosdb compatible keys

---

src/main/java/de/zalando/zmon/dataservice/DataServiceMetrics.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Count data points written, we dont track this so far.

Added a counter for points written

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/MarkWriter.java

Disable per check metrics by default

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Add kube_service_name in tag fields

Add kube_service_name in tag fields

---

pom.xml

Move to spring 1.4.4 and undertow

---

Dockerfile

Bump base image

---

src/main/resources/config/application.yaml

Enable compression for JSON responses

---

pom.xml
src/main/java/de/zalando/zmon/dataservice/TokenWrapper.java
src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/config/Oauth2Config.java
src/main/java/de/zalando/zmon/dataservice/proxies/checks/CachingCheckService.java
src/main/java/de/zalando/zmon/dataservice/proxies/checks/ChecksConfig.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithDefaultCheckServiceTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/checks/ChecksControllerWithNoOpServiceTest.java

Cache alerts and checks in data service

Added support for caching alert and check reponses

---

src/main/java/de/zalando/zmon/dataservice/proxies/checks/CachingCheckService.java

Fixing issue with timestamp stored.

Fixing stored timestamp to return orignal value

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Store this tag to allow easy filter and group by api path

Storing the path as an additional tag on the actuator time series.

---

src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java
src/main/resources/redis/scripts/checkAlerts.lua

reference lua script also updated

Added cleanup of ack state whenever the alert is no longer up

---

pom.xml

Brings repackage goal back

---

src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java
src/main/java/de/zalando/zmon/dataservice/data/RedisWorkerResultWriter.java

Skip redis write and create events only.

Skip redis

---

src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java

Should help with processing of alerts with too many entities

Replace Redis smembers call with scard for efficiency

---

src/main/java/de/zalando/zmon/dataservice/DataServiceMetrics.java
src/main/java/de/zalando/zmon/dataservice/data/AlertData.java
src/main/java/de/zalando/zmon/dataservice/data/RedisConfig.java
src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java
src/test/java/de/zalando/zmon/dataservice/data/PutDataTest.java
src/test/java/de/zalando/zmon/dataservice/data/RedisDataStoreTest.java

Expose alert duration metrics

---

README.rst
delivery.yaml
pom.xml

Updated delivery.yaml to have stable and unstable version of docker images. Added spring boot opentracing library for code instrumentation.

Changes for opentracing instrumentation

---

pom.xml
src/main/java/de/zalando/zmon/dataservice/data/KairosDataPointsQueryStore.java
src/main/java/de/zalando/zmon/dataservice/data/ProxyWriter.java
src/main/java/de/zalando/zmon/dataservice/proxies/ControllerProxy.java
src/main/java/de/zalando/zmon/dataservice/proxies/kairosdb/KairosdbProxy.java

That enables instrumentation between Data Service and: Kairos, Metric cache, Eventlog.

Adds instrumentation of apache HTTP client

---

src/main/java/de/zalando/zmon/dataservice/data/AppMetricsClient.java

Used to send requests to metrics-cache

Add instrumentation to missed async client

---

delivery.yaml
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Add namespace tag to KairosDB insert queries
https://github.com/zalando-zmon/zmon-worker/issues/333

Add namespace tag to KairosDB insert queries

---

src/main/java/de/zalando/zmon/dataservice/data/RedisDataPointsQueryStore.java

Corrected spancontextformatidentifier to 0x00 instead of 0x30

Corrected spancontextformatidentifier to 0x00 instead of 0x30

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Resolve #96 
Signed-off-by: Mohab Usama <mohab.abdelhameed@zalando.de>

Remove worker tag

---

pom.xml

upgrade surefire version and configuration

---

pom.xml
src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/AppMetricsClient.java
src/main/java/de/zalando/zmon/dataservice/data/HttpClientFactory.java
src/main/java/de/zalando/zmon/dataservice/data/HttpEventLogger.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDataPointsQueryStore.java
src/main/java/de/zalando/zmon/dataservice/data/ProxyWriter.java
src/main/java/de/zalando/zmon/dataservice/proxies/ControllerProxy.java
src/main/java/de/zalando/zmon/dataservice/proxies/kairosdb/KairosdbProxy.java

added timeouts and TTLs to all HTTP clients

---

src/main/java/de/zalando/zmon/dataservice/Application.java
src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/config/WhitelistedChecks.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java
src/main/java/de/zalando/zmon/dataservice/data/WhitelistedChecks.java
src/test/java/de/zalando/zmon/dataservice/data/KairosDbStoreTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/KairosDBTest.java

whitelisting checks for BF

---

pom.xml

use spring-boot-maven-plugin in development only

use spring-boot-maven-plugin in development only

---

pom.xml

Revert updating opentracing-spring-cloud to 0.2.4 and changing spring-boot-maven-plugin to development profile only
specifically #114 and part of #112

Revert recent changes

---

src/main/java/de/zalando/zmon/dataservice/proxies/kairosdb/KairosdbProxy.java

Issue: https://github.com/zalando-zmon/zmon-data-service/issues/117

add logging of check id

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDataPointsQueryStore.java
src/main/java/de/zalando/zmon/dataservice/proxies/kairosdb/KairosdbProxy.java

set socket timeouts to 5s

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

Add component as tag to KairosDB

Add component as tag to KairosDB

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

to get the # of changing tags in total

add entity tags to result size warning

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

add checksum of keys

---

src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

This reverts commit 38ad3207810b82ebb5f7b7df3ebd2c96a057f72a. - only meant as temporary change and it's causing latency

Revert "add checksum of keys (#124)"

---

src/main/java/de/zalando/zmon/dataservice/DataServiceMetrics.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

data-service.worker-results for overall number of POST
data-service.worker-results-batched for overall number of results

metrics for workerResults

---

src/main/java/de/zalando/zmon/dataservice/DataServiceMetrics.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

i.e. all keys non numeric -> empty

add empty count of results

---

src/main/java/de/zalando/zmon/dataservice/config/DataServiceConfigProperties.java
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java

add sampling of check keys for one specific check

---

src/main/java/de/zalando/zmon/dataservice/ApplianceVersionService.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/DefaultEntitiesService.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesController.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesService.java
src/main/java/de/zalando/zmon/dataservice/proxies/entities/NoOpEntitiesService.java
src/test/java/de/zalando/zmon/dataservice/data/DataServiceControllerTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/entities/EntitiesControllerTest.java

see also https://github.com/zalando-zmon/zmon-controller/pull/714

add exclude for entities

---

.travis.yml
src/main/java/de/zalando/zmon/dataservice/data/KairosDBStore.java
src/main/java/de/zalando/zmon/dataservice/data/MetricTiers.java
src/test/java/de/zalando/zmon/dataservice/data/KairosDbStoreTest.java
src/test/java/de/zalando/zmon/dataservice/data/MetricTiersTest.java
src/test/java/de/zalando/zmon/dataservice/proxies/KairosDBTest.java

Extend data-service's whitelisting functionality to support metric tiers

add metric tiers

---

src/main/java/de/zalando/zmon/dataservice/data/MetricTiers.java
src/test/java/de/zalando/zmon/dataservice/data/MetricTiersTest.java

to introduce "service degradation level 2.5"

make it possible to sample ingestion by tier

---

src/main/java/de/zalando/zmon/dataservice/data/MetricTiers.java
src/test/java/de/zalando/zmon/dataservice/data/MetricTiersTest.java

as an outcome of testing during load test

fix the case when sample check tier == 3 and then all tiers got sampled

---

src/main/java/de/zalando/zmon/dataservice/data/HttpEventLogger.java
src/main/java/de/zalando/zmon/dataservice/data/RedisDataStore.java

so we can properly display them in the history

fix the serialization of the JSON objects
